### ISSUE TITLE
MediaQuery.of() called with a context that does not contain a MediaQuery

### ISSUE THREAD

**Issue by zfha** [OpenFlutter/flutter_screenutil#14]
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building MainApp(dirty):
flutter: MediaQuery.of() called with a context that does not contain a MediaQuery.
flutter: No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
flutter: This can happen because you do not have a WidgetsApp or MaterialApp widget (those widgets introduce
flutter: a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.
flutter: The context used was:
flutter:   MainApp(dirty)
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      MediaQuery.of (package:flutter/src/widgets/media_query.dart:480:5)
flutter: #1      ScreenUtil.init (package:flutter_screenutil/flutter_screenutil.dart:35:44)
flutter: #2      MainApp.build (package:bmatch_flutter/main.dart:11:65)
flutter: #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:3774:28)
flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
flutter: #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
flutter: #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
flutter: #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
flutter: #10     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:909:16)
flutter: #11     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:880:5)
flutter: #12     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:826:17)
flutter: #13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
flutter: #14     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:825:13)
flutter: #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:712:7)
flutter: #16     runApp (package:flutter/src/widgets/binding.dart:756:7)
flutter: #17     main (package:bmatch_flutter/main.dart:5:16)
flutter: #18     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
flutter: #19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by lizhuoyuan** [comment]
I think , you initialization is not correct.

please show me the code.

**Comment by zfha** [comment]
```
import 'package:flutter/material.dart';
import 'package:bmatch_flutter/route/routes.dart';
import 'package:flutter/services.dart';
import 'package:bmatch_flutter/provider/auth.dart';
import 'package:bmatch_flutter/utils/adaptor.dart';

void main() async {
  runApp(new MainApp());
}

class MainApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    ScreenUtil.instance = ScreenUtil(width: 750, height: 1334)..init(context); // is wrong
    return new MaterialApp(
      title: 'My Login App',
      theme: new ThemeData(
        brightness: Brightness.light,
        primaryColorBrightness: Brightness.light,
        accentColorBrightness: Brightness.light,
        primaryColor: Colors.white,
        primaryTextTheme: TextTheme(title: TextStyle(color: Color(0xFF000000))),
      ),
      routes: routes,
    );
  }
}

```
I init before MaterailApp is wrong.
but init in a widget is OK.

**Comment by lizhuoyuan** [comment]
Be sure to set the page in the MaterialApp's home(ie the entry file, just set it once) to ensure that the fit size is set before each use.

init in first widget(route) is ok , and you only need init once.

**Comment by lixsh8** [comment]
我也遇到同样的问题
`import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

void main(){
  runApp(new HomePage());
}

class HomePage extends StatelessWidget{

  Widget _buildHome(){
    return new Container(
      width: 750,
      color: Color.fromRGBO(200, 200, 200, 1),
      child: new Image.asset('images/banner01.png')
    );
  }


  @override
  Widget build(BuildContext context) {
    //假如设计稿是按iPhone6的尺寸设计的(iPhone6 750*1334)
    ScreenUtil.instance = ScreenUtil(width: 750, height: 1334)..init(context);

    return new MaterialApp(
      title: '首页',
      home: new Scaffold(
        appBar: AppBar(
          title: new Text('首页'),
        ),
        body: _buildHome(),
      ),
    );
  }
}`

**Comment by lixsh8** [comment]
> import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

void main(){
  runApp(new HomePage());
}

class HomePage extends StatelessWidget{

  Widget _buildHome(){
    return new Container(
      width: 750,
      color: Color.fromRGBO(200, 200, 200, 1),
      child: new Image.asset('images/banner01.png')
    );
  }


  @override
  Widget build(BuildContext context) {
    //假如设计稿是按iPhone6的尺寸设计的(iPhone6 750*1334)
    ScreenUtil.instance = ScreenUtil(width: 750, height: 1334)..init(context);

    return new MaterialApp(
      title: '首页',
      home: new Scaffold(
        appBar: AppBar(
          title: new Text('首页'),
        ),
        body: _buildHome(),
      ),
    );
  }
}

**Comment by lizhuoyuan** [comment]
![image](https://user-images.githubusercontent.com/15923901/58404129-fe375680-8096-11e9-81a7-a86e8614c6c2.png)
 请在这个home里面初始化 
具体可查看example里的初始化方式

**Comment by lizhuoyuan** [comment]
@lixsh8  能放具体的错误日志以及flutter 和 库的版本吗

**Comment by lixsh8** [comment]
flutter_screenutil: ^0.5.2
flutter:1.5.4

> I/flutter (19461): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (19461): The following assertion was thrown building HomePage(dirty):
I/flutter (19461): MediaQuery.of() called with a context that does not contain a MediaQuery.
I/flutter (19461): No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
I/flutter (19461): This can happen because you do not have a WidgetsApp or MaterialApp widget (those widgets introduce
I/flutter (19461): a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.
I/flutter (19461): The context used was:
I/flutter (19461):   HomePage(dirty)
I/flutter (19461): 
I/flutter (19461): When the exception was thrown, this was the stack:
I/flutter (19461): #0      MediaQuery.of (package:flutter/src/widgets/media_query.dart:528:5)
I/flutter (19461): #1      ScreenUtil.init (package:flutter_screenutil/flutter_screenutil.dart:37:44)
I/flutter (19461): #2      HomePage.build (package:ui_xly_home/main.dart:22:65)
I/flutter (19461): #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:3789:28)
I/flutter (19461): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
I/flutter (19461): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (19461): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (19461): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (19461): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (19461): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (19461): #10     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:933:16)
I/flutter (19461): #11     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:904:5)
I/flutter (19461): #12     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:850:17)
I/flutter (19461): #13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2258:19)
I/flutter (19461): #14     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:849:13)
I/flutter (19461): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
I/flutter (19461): #16     runApp (package:flutter/src/widgets/binding.dart:780:7)
I/flutter (19461): #17     main (package:ui_xly_home/main.dart:5:3)
I/flutter (19461): #18     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:199:25)
I/flutter (19461): #23     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:190:5)
I/flutter (19461): #24     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
I/flutter (19461): #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
I/flutter (19461): (elided 4 frames from package dart:async)
I/flutter (19461): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/zygote  (19461): Ignoring second debugger -- accepting and dropping
D/EGL_emulation(19461): eglMakeCurrent: 0x9dd28a00: ver 3 0 (tinfo 0xa8f4e9d0)
D/EGL_emulation(19461): eglMakeCurrent: 0x9f904240: ver 3 0 (tinfo 0x9f903280)
E/eglCodecCommon(19461): glUtilsParamSize: unknow param 0x00008741
I/chatty  (19461): uid=10086(u0_a86) 1.gpu identical 2 lines
E/eglCodecCommon(19461): glUtilsParamSize: unknow param 0x00008741

**Comment by lixsh8** [comment]
去掉ScreenUtil.instance = ScreenUtil(width: 750, height: 1334)..init(context);这句就没问题

**Comment by lixsh8** [comment]
有时间帮我看下吗

**Comment by lizhuoyuan** [comment]
> 有时间帮我看下吗

你这个context不对啊  .
你要在_buildHome 里面初始化

**Comment by lixsh8** [comment]
_buildHome里面没有context，
我看到你的demo都是放在Widget build(BuildContext context) {}里面的
新手勿喷

**Comment by lizhuoyuan** [comment]
> _buildHome里面没有context，
> 我看到你的demo都是放在Widget build(BuildContext context) {}里面的
> 新手勿喷

你看层级不一样 , 
你是在materiapp里初始化的
我是在它的home中的组件里初始化的
