### ISSUE TITLE
多页面横竖切换问题

### ISSUE THREAD

**Issue by Flynn-X** [OpenFlutter/flutter_screenutil#269]
遇到个的问题，横竖屏幕切换，会导致所有页面进行重新build，很不合理，大家使用都没有发现这个问题麽？比如有三个页面到第三个进行横竖切换，页面回回到初始页。

**作者的example只是写了一个页面，估计没发现这个问题。**

**Comment by wang0420** [comment]
> 遇到个的问题，横竖屏幕切换，会导致所有页面进行重新build，很不合理，大家使用都没有发现这个问题麽？比如有三个页面到第三个进行横竖切换，页面回回到初始页。
> 
> **作者的example只是写了一个页面，估计没发现这个问题。**

请问你是怎么解决的

**Comment by lizhuoyuan** [comment]
@wang0420  使用第二种初始化方式应该不会有这个问题

**Comment by wang0420** [comment]
能贴下代码吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenFlutter/flutter_screenutil"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月16日(星期四) 晚上6:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenFlutter/flutter_screenutil] 多页面横竖切换问题 (#269)





 
@wang0420  使用第二种初始化方式应该不会有这个问题
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wang0420** [comment]
//设置尺寸（填写设计中设备的屏幕尺寸）如果设计基于360dp * 690dp的屏幕     ScreenUtil.init(         BoxConstraints(             maxWidth: MediaQuery.of(context).size.width,             maxHeight: MediaQuery.of(context).size.height),         designSize: Size(360, 690),         orientation: Orientation.portrait);
这样是不是在每个页面都要去初始化一次？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenFlutter/flutter_screenutil"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月16日(星期四) 晚上6:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenFlutter/flutter_screenutil] 多页面横竖切换问题 (#269)





 
@wang0420  使用第二种初始化方式应该不会有这个问题
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lizhuoyuan** [comment]
不用每个页面  
就是前后有特殊变化的需要
然后还有就是最开始记得初始化就行

**Comment by KaiLiDev** [comment]
> 遇到个问题，横竖屏切换，会导致所有页面进行重新构建，很不合理，大家使用都没有发现这个问题么？比如有三个页面到第三个进行横竖屏切换，页面回到最初页面。
> 
> **作者的例子只是写了一页，估计没有发现这个问题。**

请问下这个问题有办法处理吗？
