### ISSUE TITLE
Flutter ScreenUtil().setSp(22) doesn't work after null safety upgrade to 5.0.0+2

### ISSUE THREAD

**Issue by savanbthakkar** [OpenFlutter/flutter_screenutil#281]
We have used flutter_screenutil package in our flutter project. In current version of our application, this is how we set the fontsize, and it works fine.

`fontSize: ScreenUtil().setSp(22)
`

After upgrading this package to 5.0.0+2, suddenly fontsize changed way too small. Upon debugging, we found that ScreenUtil().setSp(22) returns 4.5. That's what it does.

The way we used to initialize ScreenUtil in old version:

```
Widget build(BuildContext context) {
    ScreenUtil.init(context, allowFontScaling: false);

```
The way we initialize now after upgrading the package:

```
Widget build(BuildContext context) {
    return ScreenUtilInit(
          designSize: Size(1080, 1920),
          builder: () => Scaffold(...

```

Is there anything wrong or are we missing anything here? How can we get the fontsize back to normal?

**Comment by lizhuoyuan** [comment]
The unit of Size(1080, 1920) is px, while the new version of the plug-in uses the size of dp.
It needs to be converted to the corresponding size

**Comment by savanbthakkar** [comment]
> The unit of Size(1080, 1920) is px, while the new version of the plug-in uses the size of dp.
> It needs to be converted to the corresponding size

Didn't work. If I change Size to anything else, it messes up the screen. It either makes the entire screen to big or too small. Do I have to go to all the places and change the Text font sizes?

**Comment by lizhuoyuan** [comment]
Only the initialization is modified.
Just switch the units of the design to dp

**Comment by debuggerx01** [comment]
https://github.com/OpenFlutter/flutter_screenutil/blob/959f18821039ac5162696f6714e11c0c9265703e/lib/screenutil.dart#L89
https://github.com/OpenFlutter/flutter_screenutil/blob/514454586ce9c87b5d371d4441b079e3eeedbad7/lib/screenutil.dart#L95

Starting from v4.0.2, `scaleText` is `min(scaleWidth, scaleHeight)`, but before this version, `scaleText` is equal to `scaleWidth`, so I think this is why the font size looks strange on some devices The reason is because the font size may be adjusted to `scaleHeight`, but in most cases, we only need to adjust the font size to scaleWidth.

@lizhuoyuan

**Comment by lizhuoyuan** [comment]
@debuggerx01 
perhaps you're right.
The teacher said that I am not sure which of the two options is the best.
