### ISSUE TITLE
Does not respond when Screen Size is changed - Windows/Linux/MacOs

### ISSUE THREAD

**Issue by Eerey** [OpenFlutter/flutter_screenutil#356]
When developing in a desktop environment, the plugin does not react to screen size changes.

This should happen by default imo.

**Comment by Mounir-Bouaiche** [comment]
Please provide more details, like screenshots, piece of your code, the OS (Windows, Linux, MacOS),...

**Comment by Mounir-Bouaiche** [comment]
I already tested it on Windows and it is still working fine.

**Comment by Mashood97** [comment]
@Mounir-Bouaiche 
I am also facing this error when i build app for mobile, tablet and desktop, The issue is i have a widget which takes mobile,desktop and tablet designs, now i have initialized screen util in each widget, the issue i am facing is I have a check box on screen 1 and when i navigate to screen two and then navigate back to screen 1 and when i tap checkbox of screen one, it shows null value error on using sp,h and w provided by screen util.

**Comment by Maadhav** [comment]
Maybe try using LayoutBuilder, I remember fixing the issue with it. LayoutBuilder should be able to react to any new changes to width and height of the application.

**Comment by Mounir-Bouaiche** [comment]
@Eerey @Mashood97 , I have recently publish the new version of the library. Go check it out and if it works fine for you please close this issue, or else drop error log here. Thank you.

**Comment by Eerey** [comment]
As I do not have time right now for further testing and you publishing a new version of it, I close my issue for now. Someone might reopen the issue of the problem still exists. Thanks @Mounir-Bouaiche for updating the library, I might come back to it very soon!
