### ISSUE TITLE
Button Text missing after updating to 5.9.0

### ISSUE THREAD

**Issue by byteripper** [OpenFlutter/flutter_screenutil#522]
After updating to 5.9.0 the text on all buttons where i use .sp was missing, but only on the release i uploaded to PlayStore.
On all connected, virtual and physical, devices there was no problem.

After going back to 5.8.4 and uploading a new update to PlayStore everything was back to normal.

Iphone user where not reporting any problems yet. So it seams to be a Android problem only.

**Comment by apriawan0104** [comment]
me too.
after update 5.9.0
my UI not render (text, padding, and other widget using service screen util)
my solution is Downgrade version to 5.8.4

**Comment by hardikkhunt905** [comment]
facing same issue on Version 5.9.0
I Downgrade version to 5.8.4

**Comment by AliHoseinpoor** [comment]
i have the same issue.

**Comment by hardikkhunt905** [comment]
minTextAdapt: true,
if you do this it may be work for me it's working on latest version and i set this in screenutils and text is showing somehow

**Comment by QixianWu** [comment]
> 在版本 5.9.0 上面临同样的问题， 我将版本降级到 5.8.4，但它对我不起作用，它仅在发布/配置文件构建中随机从按钮或普通文本中删除图像和文本，它在调试时完美工作

Ensure that your pubspec.yaml declaration is a flutter_ Screenutil: 5.8.4 instead of flutter_ Screenutil: ^ 5.8.4

**Comment by QixianWu** [comment]
> facing same issue on Version 5.9.0 I Downgrade version to 5.8.4 but it's not working for me and it's removing image and text from button or normal text randomly only in release/profile build it's perfectly working on debug

Ensure that your pubspec.yaml declaration is a flutter_ Screenutil: 5.8.4 instead of flutter_ Screenutil: ^ 5.8.4

**Comment by lurongshuang** [comment]
我也是。
更新 5.9.0 后，
我的 UI 未呈现（文本、填充和其他使用 service screen util 的小部件），
我的解决方案是将版本降级到 5.8.4

**Comment by lurongshuang** [comment]
me too.
after update 5.9.0
my solution is Downgrade version to 5.8.4

**Comment by HusseinReda97pro** [comment]
I faced an issue like this  in release mode only on Android 14, for Android 9 or ios it works fine, the issue is that screenutil  not  initiated yet so any extension used returns 0 in my case it was .sp , so the UI is rendered will, but provided value for fontSize was 0 
this makes texts disappear, 
 
In my case, this was because I used (xx.sp) in static variables, which try to calculate before screenutil initiated, so my solution Is not to use .sp in static variables instead make a class and initialize one instance from it to be used throw the app, and initiated it in screenutil  builder, this fix the issue with me
