### ISSUE TITLE
Landscape mode, font size increases causing overflow

### ISSUE THREAD

**Issue by 315574925** [OpenFlutter/flutter_screenutil#553]
Landscape mode, font size increases causing overflow

**Comment by giantss** [comment]
I also appeared, the current `flutter` version is 3.19.5

**Comment by hmartiins** [comment]
the same issue

**Comment by mozomig** [comment]
I thinks it's happens because in 3.9.0 fontSizeResolver calculate scale by width, and in landscape mode width very large and scale factor more 2. You can try override fontSizeResolver like this https://github.com/OpenFlutter/flutter_screenutil/issues/558#issuecomment-2047043378 and in landscape mode will calculate by screenSize.height / designSize.width

**Comment by hmartiins** [comment]
> I thinks it's happens because in 3.9.0 fontSizeResolver calculate scale by width, and in landscape mode width very large and scale factor more 2. You can try override fontSizeResolver like this [#558 (comment)](https://github.com/OpenFlutter/flutter_screenutil/issues/558#issuecomment-2047043378) and in landscape mode will calculate by screenSize.height / designSize.width

I applied this and it worked perfectly for my case!
